class_name UpgradeIcons
extends RefCounted
## Power-up upgrade icon lookup, by convention: `assets/upgrade_icons/<type>.png`, where
## `<type>` is one of `hp` / `attack` / `defense` / `move`.
##
## These are OPTIONAL placeholder art (generated by `tools/gen_upgrade_icons.gd`): the power-up
## chooser falls back to a flat colour swatch when a file is absent, so the game runs fine without
## them. To replace a placeholder, drop a PNG named after the upgrade type into
## `assets/upgrade_icons/` and re-run `--import` — nothing references these by path except this
## helper. See `assets/upgrade_icons/README.md` for the spec.

const DIR := "res://assets/upgrade_icons/"

# Fallback swatch colours (also the base tint the generated placeholders use).
const COLORS := {
	"hp": Color(0.85, 0.22, 0.28),
	"attack": Color(0.92, 0.55, 0.18),
	"defense": Color(0.26, 0.5, 0.9),
	"move": Color(0.62, 0.36, 0.86),
}

static var _cache: Dictionary = {}


## The icon texture for an upgrade type, or null when that type has no art yet.
static func for_type(type: String) -> Texture2D:
	if type.is_empty():
		return null
	if _cache.has(type):
		return _cache[type]
	var path := DIR + type + ".png"
	var tex: Texture2D = null
	if ResourceLoader.exists(path):
		tex = load(path) as Texture2D
	_cache[type] = tex
	return tex


## The fallback swatch colour for an upgrade type (used when for_type() is null).
static func color_for(type: String) -> Color:
	return COLORS.get(type, Color(0.5, 0.5, 0.5))


## Drop the memo (used by tests; also handy if art is added while the game is running).
static func clear_cache() -> void:
	_cache = {}
